Repository buildsec/frsca, pull requests merged in 2021-12, with the labels that each got.

#85 Update docs.yaml
  .github/workflows/docs.yaml
Labels: size/XS

#84 Apply missing git-clone task
  examples/ibm-tutorial/ibm-tutorial.sh
Labels: size/XS

#87 added wait for kyverno
  platform/30-kyverno-setup.sh
Labels: size/XS

#86 Implement new action to publish documentation
  .github/workflows/docs.yaml
Labels: size/S

#88 Fix docs build step
  .github/workflows/docs.yaml
Labels: size/XS

#89 Update the documentation
  Makefile
  docs/config.toml
  docs/content/docs/getting-started/quick-start.md
Labels: size/M

#78 Update GitHub templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: size/L

#91 Update README
  .github/CONTRIBUTING.md
  .github/stale.yml
  Makefile
  README.md
  docs/content/docs/contributing/how-to-contribute.md
  docs/content/docs/getting-started/introduction.md
  docs/content/docs/getting-started/quick-start.md
Labels: size/L

#93 add jq to mac install
  platform/00-kubernetes-minikube-setup.sh
Labels: size/XS

#96 Update 00-kubernetes-minikube-setup.sh
  platform/00-kubernetes-minikube-setup.sh
Labels: size/XS

#95 Use checksum validation in vendorme for kyverno
  platform/30-kyverno-setup.sh
  platform/vendor/kyverno/release/install.yaml
  platform/vendor/vendor.sh
  platform/vendor/vendor.yaml
  platform/vendor/vendor_kyverno.sh
Labels: size/M

#103 pinned kyverno version
  platform/vendor/kyverno/release/install.yaml
  platform/vendor/vendor.yaml
Labels: size/XS

#105 updated image and updated commit hash for kyverno
  platform/30-kyverno-setup.sh
  platform/vendor/kyverno/release/install.yaml
  platform/vendor/vendor.yaml
Labels: size/L

#104 Address quick-start.md issues
  .github/workflows/install-ssf.yaml
  docs/content/docs/getting-started/quick-start.md
Labels: size/S

#107 Coverting sample-pipeline to cue
  Makefile
  examples/examples.cue
  examples/sample-pipeline/README.md
  examples/sample-pipeline/pipeline-account.yaml
  examples/sample-pipeline/registry-secret.yaml
  examples/sample-pipeline/sample-pipeline.cue
  examples/sample-pipeline/sample-pipeline.sh
  examples/sample-pipeline/ssf-pipeline.yaml
  examples/sample-pipeline/ssf-run.yaml
  examples/sample-pipeline/ssf-verify.pub
  examples/sample-pipeline/task-build-push-image.yaml
  examples/sample-pipeline/task-deploy.yaml
  examples/sample-pipeline/task-git-clone.yaml
  examples/sample-pipeline/task-gyrpe-scan.yaml
  examples/sample-pipeline/task-syft-bom-generation.yaml
  ssf.cue
  ssf_tool.cue
Labels: size/XXL

#98 Fix markdown linter errors
  Makefile
  README.old.md
  demos/ocidemo/README.md
  examples/sample-pipeline/README.md
  tools/install-ci.sh
Labels: size/L
