Repository buildsec/frsca, pull requests merged in 2021-11, with the labels that each got.

#81 Move vendoring of tekton + chains to vendorme
  platform/vendor/vendor.sh
  platform/vendor/vendor.yaml
  platform/vendor/vendor_tekton_chains.sh
  platform/vendor/vendor_tekton_pipeline.sh
Labels: size/M

#83 ignore generated cosign.pub key generated from ocidemo
  .gitignore
Labels: size/XS

#80 Add kodiak configuration
  .github/.kodiak.toml
Labels: size/S, do-not-merge

#82 Implement a documentation GitHub workflow
  .github/workflows/docs.yaml
  .github/workflows/install-ssf.yaml
  .gitignore
  Makefile
Labels: size/M
