Repository buildsec/frsca, pull requests merged in 2022-08, with the labels that each got.

#281 update version tekton-pipeline
  platform/vendor/tekton/pipeline/release.yaml
  platform/vendor/vendor.yaml
Labels: size/L

#282 Add Zola package to shell.nix
  shell.nix
Labels: size/XS

#283 Change introduction page to zola shortcode
  README.md
  docs/content/docs/getting-started/introduction.md
  docs/templates/docs/page.html
  docs/templates/shortcodes/markdown.html
Labels: size/M

#286 Bumping versions
  .github/workflows/docs.yaml
  .github/workflows/install-frsca.yaml
  go.mod
Labels: size/S

#284 Pull up ca-certs volumes
  examples/cosign/task-ko.yaml
  examples/examples.cue
  examples/sample-pipeline/sample-pipeline.cue
Labels: size/M

#288 Add Dependabot
  .github/dependabot.yml
Labels: size/XS

#287 Update kyverno v1.7.1 -> v1.7.2
  platform/vendor/kyverno/release/install.yaml
  platform/vendor/vendor.yaml
Labels: size/M

#290 Bumping zola version
  .github/workflows/docs.yaml
  docs/serve.sh
Labels: size/XS

#293 Make the image link relative
  docs/content/docs/getting-started/architecture.md
Labels: size/XS

#296 Update README to make FRSCA clearer
  README.md
Labels: size/L

#294 update script to use INSTALL_DIR
  platform/00-kubernetes-minikube-setup.sh
Labels: size/XS

#295 update tekton pipeline v0.38.2
  platform/vendor/tekton/pipeline/release.yaml
  platform/vendor/vendor.yaml
Labels: size/M

#301 update tekton chains version v0.11.0
  platform/vendor/tekton/chains/release.yaml
  platform/vendor/vendor.yaml
Labels: size/S

#297 Break out scripts to install and setup
  .github/workflows/install-frsca.yaml
  Makefile
  platform/10-tekton-pipelines-install.sh
  platform/11-tekton-pipeline-setup.sh
  platform/12-tekton-chains-install.sh
  platform/13-tekton-chains-setup.sh
  platform/14-tekton-tasks.sh
  platform/20-spire-install.sh
  platform/21-spire-setup.sh
  platform/30-kyverno-install.sh
  platform/31-kyverno-setup.sh
  platform/35-opa-gatekeeper-setup.sh
Labels: size/L

#309 Update docker run commands to be selinux friendly
  docs/serve.sh
  platform/02-setup-certs.sh
Labels: size/XS

#306 Update grype v0.35.0 -> v0.46.0
  examples/examples.cue
Labels: size/XS

#310 Update ko image -> 14b4fe1
  examples/cosign/task-ko.yaml
Labels: size/XS

#314 Remove docker/config.json dependency
  platform/31-kyverno-setup.sh
  platform/35-opa-gatekeeper-setup.sh
  resources/docker-config-empty.json
Labels: size/XS

#315 Replace icr.io reference
  examples/sample-pipeline/sample-pipeline.cue
Labels: size/XS
