Repository buildsec/frsca, pull requests merged in 2022-11, with the labels that each got.

#355 Upgrade Spire to use CSI driver
  platform/components/spire/values.yaml
  platform/components/tekton/chains/patch_spire.json
  platform/vendor/spire/chart/Chart.yaml
  platform/vendor/spire/chart/templates/agent-configmap.yaml
  platform/vendor/spire/chart/templates/agent-daemonset.yaml
  platform/vendor/spire/chart/templates/server-configmap.yaml
  platform/vendor/spire/chart/templates/server-statefulset.yaml
  platform/vendor/spire/chart/templates/spiffe-csi-driver.yaml
  platform/vendor/spire/chart/values.yaml
  platform/vendor/vendor-helm-all.sh
Labels: size/L

#358 Fix minikube install on MacOS
  platform/00-kubernetes-minikube-setup.sh
Labels: size/XS

#364 install crane in minikube-setup for mac
  platform/00-kubernetes-minikube-setup.sh
Labels: size/XS

#365 Drop Tekton Dashboard
  platform/10-tekton-pipelines-install.sh
  platform/vendor/tekton/dashboard/tekton-dashboard-release.yaml
  platform/vendor/vendor.yaml
Labels: size/L

#367 Bump Tekton Chains to 0.13.0
  platform/vendor/tekton/chains/release.yaml
  platform/vendor/vendor.yaml
Labels: size/S
