Repository buildsec/frsca, pull requests merged in 2022-03, with the labels that each got.

#148 Implemented Maven-pipeline
  Makefile
  examples/maven/README.md
  examples/maven/maven-run.yaml
  examples/maven/maven.sh
  examples/maven/maven.yaml
  platform/vendor/tekton/catalog/main/task/maven/0.2/maven.yaml
  platform/vendor/vendor.yaml
Labels: size/L

#153 Update vendorme
  platform/vendor/vendor.sh
  platform/vendor/vendor.yaml
Labels: size/XS

#159 updated kyverno to 1.6.1 and added keyless verification
  cue.mod/gen/github.com/kyverno/kyverno/api/kyverno/v1/policy_types_go_gen.cue
  cue.mod/gen/k8s.io/api/rbac/v1/types_go_gen.cue
  cue.mod/gen/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types_jsonschema_go_gen.cue
  cue.mod/gen/k8s.io/apimachinery/pkg/apis/meta/v1/group_version_go_gen.cue
  cue.mod/gen/k8s.io/apimachinery/pkg/apis/meta/v1/types_go_gen.cue
  cue.mod/gen/k8s.io/apimachinery/pkg/runtime/interfaces_go_gen.cue
  go.mod
  go.sum
  platform/vendor/kyverno/release/install.yaml
  platform/vendor/vendor.yaml
  resources/kyverno/admission-control-policy/admission-control-verify-attestation.cue
  resources/kyverno/admission-control-policy/admission-control-verify-image-resources.cue
  resources/kyverno/admission-control-policy/admission-control-verify-image.cue
Labels: size/L

#154 Update validation
  .github/workflows/install-ssf.yaml
  docs/content/docs/getting-started/quick-start.md
  examples/buildpacks/README.md
  examples/go-pipeline/README.md
  examples/ibm-tutorial/README.md
  examples/sample-pipeline/README.md
Labels: size/L

#160 Refactor grype task
  examples/sample-pipeline/sample-pipeline.cue
Labels: size/M

#165 Skip chains install if signing-secrets is immutable
  platform/11-tekton-chains.sh
Labels: size/XS

#166 Fix IMAGE_URL usage by crane
  .github/workflows/install-ssf.yaml
  docs/content/docs/getting-started/quick-start.md
  examples/buildpacks/README.md
  examples/go-pipeline/README.md
  examples/ibm-tutorial/README.md
  examples/sample-pipeline/README.md
Labels: size/S

#161 Simplify sample-pipeline
  examples/sample-pipeline/README.md
  examples/sample-pipeline/sample-pipeline.cue
  examples/sample-pipeline/sample-pipeline.sh
Labels: size/L
