Repository buildsec/frsca, pull requests merged in 2022-10, with the labels that each got.

#337 Switch to buildsec/vendorme
  platform/vendor/vendor.sh
Labels: size/XS

#318 Tekton triggers
  .github/workflows/install-frsca.yaml
  Makefile
  cue.mod/gen/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/cluster_trigger_binding_types_go_gen.cue
  cue.mod/gen/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/doc_go_gen.cue
  cue.mod/gen/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/event_listener_types_go_gen.cue
  cue.mod/gen/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/interceptor_types_go_gen.cue
  cue.mod/gen/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/param_go_gen.cue
  cue.mod/gen/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/trigger_binding_interface_go_gen.cue
  cue.mod/gen/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/trigger_binding_types_go_gen.cue
  cue.mod/gen/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/trigger_defaults_go_gen.cue
  cue.mod/gen/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/trigger_template_types_go_gen.cue
  cue.mod/gen/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/trigger_types_go_gen.cue
  cue.mod/gen/google.golang.org/grpc/codes/codes_go_gen.cue
  dependencies.go
  examples/buildpacks/buildpacks-run.sh
  examples/buildpacks/buildpacks-setup.sh
  examples/buildpacks/buildpacks.cue
  examples/cosign/cosign.cue
  examples/examples.cue
  examples/go-pipeline/go-pipeline-run.sh
  examples/go-pipeline/go-pipeline-setup.sh
  examples/go-pipeline/go-pipeline.cue
  examples/gradle-pipeline/gradle-pipeline-run.sh
  examples/gradle-pipeline/gradle-pipeline-setup.sh
  examples/gradle-pipeline/gradle-pipeline.cue
  examples/gradle-pipeline/gradle-pipeline.sh
  examples/ibm-tutorial/ibm-tutorial-run.sh
  examples/ibm-tutorial/ibm-tutorial-setup.sh
  examples/ibm-tutorial/ibm-tutorial.cue
  examples/maven/maven-pkg.cue
  examples/maven/maven-run.sh
  examples/maven/maven-run.yaml
  examples/maven/maven-setup.sh
  examples/maven/maven.sh
  examples/maven/maven.yaml
  examples/sample-pipeline/sample-pipeline-run.sh
  examples/sample-pipeline/sample-pipeline-setup.sh
  examples/sample-pipeline/sample-pipeline.cue
  frsca.cue
  go.mod
  go.sum
  platform/07-gitea-setup.sh
  platform/10-tekton-pipelines-install.sh
  platform/components/gitea/values.yaml
  platform/components/tekton/triggers/rbac.yaml
  platform/vendor/tekton/triggers/interceptors.yaml
  platform/vendor/tekton/triggers/release.yaml
  platform/vendor/vendor.yaml
Labels: size/XXL

#340 update kaniko task based up on catalog change
  platform/vendor/tekton/catalog/main/task/kaniko/0.6/kaniko.yaml
  platform/vendor/vendor.yaml
Labels: size/XS

#338 add new logo for frsca
  .markdownlint.yml
  README.md
  frsca_mascot-color.png
Labels: size/XS

#326 Refactor makefile to separate use cases
  Makefile
  README.md
  platform/50-example-mirror.sh
Labels: size/L

#343 Bump shfmt installer to v2
  .github/workflows/install-frsca.yaml
Labels: size/XS

#329 Improve support for internal registry
  .github/workflows/install-frsca.yaml
  examples/buildpacks/README.md
  examples/cosign/README.md
  examples/go-pipeline/README.md
  examples/gradle-pipeline/README.md
  examples/ibm-tutorial/README.md
  examples/sample-pipeline/README.md
  examples/sample-pipeline/sample-pipeline.cue
Labels: size/L

#346 Use the syft multi-platform image digest
  examples/sample-pipeline/sample-pipeline.cue
Labels: size/XS

#347 Fix documentation logo
  docs/content/docs/getting-started/frsca_mascot-color.png
Labels: size/XS

#348 Add logo as static asset
  docs/static/img/frsca_mascot-color.png
Labels: size/XS

#349 Update provenance.sh for cosign 1.5.1+
  scripts/provenance.sh
Labels: size/S

#352 Pin minikube install to version 1.26.1
  platform/00-kubernetes-minikube-setup.sh
Labels: size/XS

#356 Bump kyverno to 1.7.5
  platform/vendor/kyverno/release/install.yaml
  platform/vendor/vendor.yaml
Labels: size/L
