Repository buildsec/frsca, pull requests merged in 2022-05, with the labels that each got.

#208 Update minikube to v1.25.2
  platform/00-kubernetes-minikube-setup.sh
Labels: size/XS

#211 Remove demo folder
  demos/build_with_ebpf/attacker_project/Cargo.lock
  demos/build_with_ebpf/attacker_project/Cargo.toml
  demos/build_with_ebpf/attacker_project/src/main.rs
  demos/build_with_ebpf/bad_cargo/Cargo.lock
  demos/build_with_ebpf/bad_cargo/Cargo.toml
  demos/build_with_ebpf/bad_cargo/build-docker.sh
  demos/build_with_ebpf/bad_cargo/build.sh
  demos/build_with_ebpf/bad_cargo/hijack-inputs.Dockerfile
  demos/build_with_ebpf/bad_cargo/hijack-outputs.Dockerfile
  demos/build_with_ebpf/bad_cargo/real-cargo.Dockerfile
  demos/build_with_ebpf/bad_cargo/src/inputs/main.rs
  demos/build_with_ebpf/bad_cargo/src/outputs/main.rs
  demos/build_with_ebpf/bad_cargo/src/overwrite_binary/main.rs
  demos/build_with_ebpf/bad_cargo/src/overwrite_source/main.rs
  demos/build_with_ebpf/containers/hijack_inputs_build/default.nix
  demos/build_with_ebpf/containers/hijack_outputs_build/default.nix
  demos/build_with_ebpf/containers/real_project/default.nix
  demos/build_with_ebpf/real_project/Cargo.lock
  demos/build_with_ebpf/real_project/Cargo.toml
  demos/build_with_ebpf/real_project/src/main.rs
  demos/ocidemo/.dockerignore
  demos/ocidemo/.gitignore
  demos/ocidemo/Cargo.lock
  demos/ocidemo/Cargo.toml
  demos/ocidemo/Dockerfile
  demos/ocidemo/Makefile
  demos/ocidemo/README.md
  demos/ocidemo/src/main.rs
Labels: size/L

#217 Fix typo in examples/cosign/README.md
  examples/cosign/README.md
Labels: size/XS

#226 Change SSF to FRSCA
  .github/CONTRIBUTING.md
  .github/workflows/install-frsca.yaml
  .gitignore
  Makefile
  README.md
  cspell.config.yaml
  cue.mod/module.cue
  docs/README.md
  docs/config.toml
  docs/content/docs/getting-started/quick-start.md
  docs/content/docs/help/using-cue.md
  docs/diagrams/workspace.dsl
  docs/diagrams/workspace.json
  examples/buildpacks/buildpacks.cue
  examples/buildpacks/dual-storage-backend.md
  examples/cosign/cosign.cue
  examples/examples.cue
  examples/go-pipeline/README.md
  examples/go-pipeline/go-pipeline.cue
  examples/gradle-pipeline/README.md
  examples/gradle-pipeline/gradle-pipeline.cue
  examples/ibm-tutorial/ibm-tutorial.cue
  examples/maven/README.md
  examples/maven/maven-pkg.cue
  examples/sample-pipeline/README.md
  examples/sample-pipeline/sample-pipeline.cue
  frsca-words.txt
  frsca.cue
  frsca_tool.cue
  go.mod
  resources/kyverno/admission-control-policy/admission-control-verify-attestation.cue
  resources/kyverno/admission-control-policy/admission-control-verify-image-resources.cue
  resources/kyverno/admission-control-policy/admission-control-verify-image.cue
  resources/kyverno/admission-control-policy/kyverno.cue
Labels: size/L

#228 update tekton pipeline version
  platform/vendor/tekton/pipeline/release.yaml
  platform/vendor/vendor.yaml
Labels: size/M

#229 Changed SSF to Factory for Repeatable Secure Creation of Artifacts
  .github/CONTRIBUTING.md
  README.md
  cspell.config.yaml
  docs/config.toml
  docs/content/_index.md
  docs/content/docs/_index.md
  docs/content/docs/contributing/_index.md
  docs/content/docs/help/using-cue.md
  docs/diagrams/workspace.dsl
Labels: size/M
