Repository buildsec/frsca, pull requests merged in 2022-01, with the labels that each got.

#111 Only check kubectl version on client
  platform/00-kubernetes-minikube-setup.sh
Labels: size/XS

#112 Fix link to SSF Reference Architecture
  README.md
Labels: size/XS

#114 Fix usage of repository tag in examples
  docs/content/docs/help/using-cue.md
  examples/buildpacks/buildpacks.sh
  examples/sample-pipeline/README.md
  examples/sample-pipeline/sample-pipeline.sh
Labels: size/S

#116 added cosign to pull public key from secrets
  .github/workflows/install-ssf.yaml
  platform/30-kyverno-setup.sh
  resources/kyverno/admission-control-policy/kyverno_tool.cue
  resources/kyverno/admission-control-policy/released/configmap-keys.json
  resources/kyverno/admission-control-policy/released/verify-attestation.json
  resources/kyverno/admission-control-policy/released/verify-signature.json
Labels: size/L

#117 removed unused chains patch. Using in-toto and OCI
  platform/11-tekton-chains.sh
  platform/components/tekton/chains/patch_config_intoto.yaml
  platform/components/tekton/chains/patch_config_oci.yaml
  platform/vendor/tekton/chains/release.yaml
  platform/vendor/vendor.yaml
Labels: size/M

#123 Update Tekton Chains to v0.7.0
  platform/vendor/tekton/chains/release.yaml
  platform/vendor/vendor.yaml
Labels: size/M

#122 Add dual storage backend tutorial
  examples/buildpacks/README.md
  examples/buildpacks/dual-storage-backend.md
  platform/11-tekton-chains.sh
  platform/components/tekton/chains/patch_config_dual_backend.yaml
Labels: size/L

#121 Edit and listed yaml files, Add task in Makefile
  .github/stale.yml
  .github/workflows/docs.yaml
  .github/workflows/install-ssf.yaml
  .yamllint.yaml
  Makefile
  platform/components/tekton/chains/patch_config_oci.yaml
  resources/opa-gatekeeper/enable-mutating.yaml
Labels: size/M

#115 Development Golang pipeline
  Makefile
  examples/go-pipeline/README.md
  examples/go-pipeline/go-pipeline.cue
  examples/go-pipeline/go-pipeline.sh
  platform/vendor/tekton/catalog/main/task/kaniko/kaniko.yaml
Labels: size/L

#119 updated sample-pipeline and kyverno based on chains update. Added Sample-pipeline to integration test
  .github/workflows/install-ssf.yaml
  examples/examples.cue
  examples/sample-pipeline/README.md
  examples/sample-pipeline/sample-pipeline.cue
  examples/sample-pipeline/sample-pipeline.sh
  resources/kyverno/admission-control-policy/admission-control-verify-attestation.cue
  ssf.cue
  ssf_tool.cue
Labels: size/M
