Repository buildsec/frsca, pull requests merged in 2022-04, with the labels that each got.

#177 Update Kyverno to v1.6.2
  platform/vendor/kyverno/release/install.yaml
  platform/vendor/vendor.yaml
Labels: size/M

#169 Vendor Tekton catalog task manifests
  examples/go-pipeline/go-pipeline.sh
  platform/vendor/tekton/catalog/main/task/golang-build/0.3/golang-build.yaml
  platform/vendor/tekton/catalog/main/task/golang-test/0.2/golang-test.yaml
  platform/vendor/tekton/catalog/main/task/trivy-scanner/0.1/trivy-scanner.yaml
  platform/vendor/vendor.yaml
Labels: size/L

#174 Update Tekton CLI (tkn) to v0.23.1
  platform/00-kubernetes-minikube-setup.sh
Labels: size/XS

#176 Cleanup maven YAML
  examples/maven/maven-run.yaml
  examples/maven/maven.yaml
Labels: size/S

#155 Gradle pipeline
  Makefile
  examples/gradle-pipeline/README.md
  examples/gradle-pipeline/gradle-pipeline.cue
  examples/gradle-pipeline/gradle-pipeline.sh
  platform/vendor/tekton/catalog/main/task/jib-gradle/0.4/jib-gradle.yaml
  platform/vendor/vendor.yaml
Labels: size/L

#183 Updating vendor details for kaniko
  platform/vendor/tekton/catalog/main/task/kaniko/0.6/kaniko.yaml
  platform/vendor/vendor.yaml
Labels: size/XS

#185 Update Tekton Dashboard to v0.25.0
  platform/vendor/tekton/dashboard/tekton-dashboard-release.yaml
  platform/vendor/vendor.yaml
Labels: size/S

#188 Teardown local dev environment
  Makefile
  README.md
Labels: size/S

#190 Update cosign to v1.7.1
  platform/00-kubernetes-minikube-setup.sh
Labels: size/XS

#172 Merging config from CUE and YAML
  docs/content/docs/help/using-cue.md
  examples/buildpacks/buildpacks.cue
  examples/buildpacks/buildpacks.sh
  examples/examples.cue
  examples/go-pipeline/go-pipeline.cue
  examples/go-pipeline/go-pipeline.sh
  examples/gradle-pipeline/gradle-pipeline.cue
  examples/gradle-pipeline/gradle-pipeline.sh
  examples/ibm-tutorial/ibm-tutorial.cue
  examples/ibm-tutorial/ibm-tutorial.sh
  examples/maven/maven-pkg.cue
  examples/maven/maven.sh
  examples/sample-pipeline/sample-pipeline.cue
  examples/sample-pipeline/sample-pipeline.sh
  platform/30-kyverno-setup.sh
  resources/kyverno/admission-control-policy/admission-control-verify-attestation.cue
  resources/kyverno/admission-control-policy/admission-control-verify-image-resources.cue
  resources/kyverno/admission-control-policy/admission-control-verify-image.cue
  resources/kyverno/admission-control-policy/kyverno.cue
  ssf.cue
  ssf_tool.cue
Labels: size/L

#193 Added EFK stack
  Makefile
  platform/40-efk-stack-setup/40-efk-stack-setup.sh
  platform/40-efk-stack-setup/README.md
  platform/components/elastic/values.yaml
Labels: size/M

#194 Vendor git-clone v0.6
  examples/buildpacks/buildpacks.sh
  examples/go-pipeline/go-pipeline.sh
  examples/gradle-pipeline/gradle-pipeline.sh
  examples/ibm-tutorial/ibm-tutorial.sh
  examples/maven/maven.sh
  examples/sample-pipeline/sample-pipeline.sh
  platform/vendor/tekton/catalog/main/task/git-clone/0.6/git-clone.yaml
  platform/vendor/vendor.yaml
Labels: size/M

#163 Add end-to-end example
  Makefile
  examples/cosign/README.md
  examples/cosign/cosign.cue
  examples/cosign/cosign.sh
  examples/cosign/cyclonedx.sbom
  examples/cosign/pipeline-ko.yaml
  examples/cosign/spdx.sbom
  examples/cosign/task-ko.yaml
  examples/examples.cue
  examples/sample-pipeline/sample-pipeline.cue
  platform/00-kubernetes-minikube-setup.sh
  platform/components/tekton/chains/patch_config_oci.yaml
  resources/kyverno/admission-control-policy/admission-control-verify-image.cue
Labels: size/XXL

#200 Update CUE to v0.4.3
  platform/00-kubernetes-minikube-setup.sh
Labels: size/XS

#199 Make the Maven pipeline build less verbose
  examples/maven/maven.yaml
Labels: size/XS

#205 Deploy Kyverno to check provenance of Tekton
  .github/workflows/install-ssf.yaml
  Makefile
  docs/content/docs/getting-started/quick-start.md
  examples/go-pipeline/README.md
  examples/gradle-pipeline/README.md
  examples/ibm-tutorial/README.md
  examples/maven/README.md
  examples/sample-pipeline/README.md
  platform/11-tekton-chains.sh
  platform/vendor/tekton/pipeline/release.yaml
  platform/vendor/vendor.yaml
  resources/kyverno/admission-control-policy/admission-control-verify-attestation.cue
  resources/kyverno/admission-control-policy/admission-control-verify-image.cue
  scripts/gen-keys.sh
Labels: size/L

#204 Update Syft to v0.44.1
  examples/sample-pipeline/sample-pipeline.cue
Labels: size/XS

#203 Update Grype to v0.35.0
  examples/examples.cue
Labels: size/XS

#198 Update the homebrew tap for CUE
  platform/00-kubernetes-minikube-setup.sh
Labels: size/XS
