Repository buildsec/frsca, pull requests merged in 2022-09, with the labels that each got.

#321 Code of conduct
  CODE_OF_CONDUCT.md
Labels: size/L

#328 Update cosign v1.8.0 -> v1.12.0
  .github/workflows/install-frsca.yaml
  examples/sample-pipeline/sample-pipeline.cue
  platform/00-kubernetes-minikube-setup.sh
Labels: size/XS

#327 Bump kyverno to 1.7.3
  platform/vendor/kyverno/release/install.yaml
  platform/vendor/vendor.yaml
Labels: size/M

#322 Specify type in cosign verify-attestation
  docs/content/docs/getting-started/quick-start.md
  examples/buildpacks/README.md
  examples/buildpacks/dual-storage-backend.md
  examples/cosign/README.md
  examples/go-pipeline/README.md
  examples/gradle-pipeline/README.md
  examples/ibm-tutorial/README.md
  examples/sample-pipeline/README.md
Labels: size/S

#330 Stop using deprecated flag `service-account-api-audiences`
  platform/00-kubernetes-minikube-setup.sh
Labels: size/XS

#333 Pin minikube to 1.25.2 in shell.nix
  shell.nix
Labels: size/S

#331 Update minikube v1.25.2 -> v1.26.1
  platform/00-kubernetes-minikube-setup.sh
Labels: size/S
