Repository buildsec/frsca, pull requests merged in 2022-02, with the labels that each got.

#129 Check vendoring has been done correctly
  .github/workflows/install-ssf.yaml
Labels: size/XS

#125 Consolidate tag definitions for examples
  examples/buildpacks/buildpacks.cue
  examples/examples.cue
  examples/go-pipeline/go-pipeline.cue
  examples/sample-pipeline/sample-pipeline.cue
Labels: size/S

#128 Update Tekton Pipeline to v0.32.1
  platform/vendor/tekton/pipeline/release.yaml
  platform/vendor/vendor.yaml
Labels: size/L

#124 Shell linter
  Makefile
  docs/bootstrap.sh
  platform/00-kubernetes-minikube-setup.sh
  platform/10-tekton-setup.sh
  platform/20-spire-setup.sh
  scripts/gen-keys.sh
  scripts/provenance.sh
Labels: size/M

#133 Update Tekton Chains to v0.8.0
  platform/vendor/tekton/chains/release.yaml
  platform/vendor/vendor.yaml
Labels: size/M

#134 Update to Kyverno v1.6.0
  platform/30-kyverno-setup.sh
  platform/vendor/kyverno/release/install.yaml
  platform/vendor/vendor.yaml
Labels: size/XL

#136 Fix linting errors
  .editorconfig
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/workflows/install-ssf.yaml
  .markdownlint.yml
  .prettierignore
  .yamllint.yaml
  Makefile
  README.md
  demos/build_with_ebpf/bad_cargo/build-docker.sh
  demos/build_with_ebpf/bad_cargo/build.sh
  demos/ocidemo/README.md
  docs/content/docs/getting-started/quick-start.md
  docs/content/docs/help/faq.md
  docs/content/docs/help/using-cue.md
  examples/buildpacks/README.md
  examples/buildpacks/dual-storage-backend.md
  examples/go-pipeline/README.md
  examples/ibm-tutorial/README.md
  examples/sample-pipeline/README.md
  platform/vendor/vendor_spire_quickstart.sh
Labels: size/L

#138 Allow ibm-tutorial example to use vendored kaniko.yaml
  examples/ibm-tutorial/ibm-tutorial.cue
  examples/ibm-tutorial/ibm-tutorial.sh
Labels: size/XS

#137 Revert "Update Tekton Pipeline to v0.32.1 (#128)"
  platform/vendor/tekton/pipeline/release.yaml
  platform/vendor/vendor.yaml
Labels: size/L

#140 Setup CSpell
  Makefile
  cspell.config.yaml
  demos/ocidemo/Makefile
  docs/config.toml
  docs/content/_index.md
  examples/buildpacks/dual-storage-backend.md
  examples/sample-pipeline/README.md
  ssf-words.txt
Labels: size/L

#139 Use kubectl rollout status to wait for deployments
  platform/10-tekton-setup.sh
  platform/11-tekton-chains.sh
  platform/30-kyverno-setup.sh
Labels: size/M

#126 Update sample-pipeline
  examples/sample-pipeline/README.md
  examples/sample-pipeline/sample-pipeline.cue
Labels: size/M

#141 Finalize the double storage tutorial
  examples/buildpacks/dual-storage-backend.md
  ssf-words.txt
Labels: size/S

#143 Enable minikube ingress addon
  platform/00-kubernetes-minikube-setup.sh
Labels: size/S

#144 Vendor tekton dashboard v0.24.1
  platform/10-tekton-setup.sh
  platform/vendor/tekton/dashboard/tekton-dashboard-release.yaml
  platform/vendor/vendor.yaml
Labels: size/L
