Repository buildsec/frsca, pull requests merged in 2022-07, with the labels that each got.

#248 Update buildpacks pipeline param ENV_VARS
  examples/buildpacks/buildpacks.cue
Labels: size/XS

#237 Updated Tekton Pipeline to v0.36.0
  platform/vendor/tekton/pipeline/release.yaml
  platform/vendor/vendor.yaml
Labels: size/L

#252 Update buildpacks pipeline to v0.2
  examples/buildpacks/buildpacks.cue
  platform/12-tekton-tasks.sh
  platform/vendor/tekton/catalog/main/pipeline/buildpacks/0.2/buildpacks.yaml
  platform/vendor/tekton/catalog/main/task/buildpacks-phases/0.2/buildpacks-phases.yaml
  platform/vendor/vendor.yaml
Labels: size/S

#254 Add server-side flag to fix max annotation length
  platform/02-setup-certs.sh
Labels: size/S

#247 Fix checksum linux
  platform/00-kubernetes-minikube-setup.sh
Labels: size/S

#258 Addresses issue #256 - missing setup-frsca in documentation
  docs/content/docs/getting-started/quick-start.md
Labels: size/S

#261 Add shell.nix for dev
  shell.nix
Labels: size/S

#260 Use bash in a way that doesn’t assume its location
  Makefile
  docs/bootstrap.sh
  examples/buildpacks/buildpacks.sh
  examples/cosign/cosign.sh
  examples/go-pipeline/go-pipeline.sh
  examples/gradle-pipeline/gradle-pipeline.sh
  examples/ibm-tutorial/ibm-tutorial.sh
  examples/maven/maven.sh
  examples/sample-pipeline/sample-pipeline.sh
  platform/00-kubernetes-minikube-setup.sh
  platform/02-setup-certs.sh
  platform/04-registry-setup.sh
  platform/05-registry-proxy.sh
  platform/10-tekton-setup.sh
  platform/11-tekton-chains.sh
  platform/12-tekton-tasks.sh
  platform/20-spire-setup.sh
  platform/25-vault-install.sh
  platform/26-vault-setup.sh
  platform/30-kyverno-setup.sh
  platform/31-opa-gatekeeper-setup.sh
  platform/40-efk-stack-setup/40-efk-stack-setup.sh
  platform/vendor/vendor-helm-all.sh
  platform/vendor/vendor-helm-chart.sh
  platform/vendor/vendor.sh
  tools/install-ci.sh
Labels: size/M

#255 Use buildpacks task from Tekton Catalog
  platform/12-tekton-tasks.sh
  platform/vendor/tekton/catalog/main/task/buildpacks/0.5/buildpacks.yaml
  platform/vendor/vendor.yaml
Labels: size/M

#262 Serve docs using docker to remove mac dependency
  Makefile
  docs/bootstrap.sh
  docs/serve.sh
Labels: size/M

#266 Allow grype to ignore some vulnerabilities
  examples/cosign/cosign.cue
  examples/cosign/pipeline-ko.yaml
  examples/examples.cue
  examples/sample-pipeline/sample-pipeline.cue
  platform/vendor/kyverno/release/install.yaml
  platform/vendor/vendor.yaml
Labels: size/L

#264 Update documentation on registry
  docs/content/docs/getting-started/quick-start.md
  docs/content/docs/help/using-cue.md
Labels: size/S

#268 Unignore CVE-2022-30065
  examples/examples.cue
Labels: size/XS

#270 Moving sample-pipeline to buildsec repo
  examples/sample-pipeline/sample-pipeline.cue
Labels: size/XS

#271 Moving example-buildpacks to buildsec repo
  examples/buildpacks/buildpacks.cue
Labels: size/XS

#272 Moving example-golang-pipeline to buildsec repo
  examples/go-pipeline/go-pipeline.cue
Labels: size/XS

#273 Moving example-gradle-pipeline to buildsec repo
  examples/gradle-pipeline/gradle-pipeline.cue
Labels: size/XS

#274 Moving example-ibm-tutorial to buildsec repo
  examples/ibm-tutorial/ibm-tutorial.cue
Labels: size/XS

#275 Moving example-maven to buildsec repo
  examples/maven/maven.yaml
Labels: size/XS

#279 Fix linting errors
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: size/XS

#259 Fix make file to install jq when running on linux host
  platform/00-kubernetes-minikube-setup.sh
Labels: size/S

#267 Documenting the FRSCA architecture
  docs/content/docs/getting-started/architecture.md
  docs/diagrams/frsca.url
  docs/static/img/frsca.png
Labels: size/M
