Repository buildsec/frsca, pull requests merged in 2022-06, with the labels that each got.

#94 Vault setup with Spire OIDC
  .github/workflows/install-frsca.yaml
  Makefile
  docs/content/docs/getting-started/quick-start.md
  examples/buildpacks/README.md
  examples/cosign/README.md
  examples/go-pipeline/README.md
  examples/gradle-pipeline/README.md
  examples/ibm-tutorial/README.md
  examples/maven/README.md
  examples/sample-pipeline/README.md
  platform/.gitignore
  platform/06-setup-certs.sh
  platform/11-tekton-chains.sh
  platform/20-spire-setup.sh
  platform/25-vault-install.sh
  platform/26-vault-setup.sh
  platform/30-kyverno-setup.sh
  platform/components/spire/values.yaml
  platform/components/tekton/chains/patch_config_kms.yaml
  platform/components/tekton/chains/patch_spire.json
  platform/components/vault/values.yaml
  platform/vault/.gitignore
Labels: size/L

#240 Temporarily switch to sha256 for vendor validation
  platform/vendor/vendor.yaml
Labels: size/S

#241 Change deprecated kyverno flag —webhooktimeout
  platform/components/kyverno/patch_container_args.json
Labels: size/XS

#242 Update vendorme
  platform/vendor/vendor.sh
  platform/vendor/vendor.yaml
Labels: size/S

#239 Update Kyverno
  platform/vendor/kyverno/release/install.yaml
  platform/vendor/vendor.yaml
Labels: size/XXL
