Repository buildsec/frsca, pull requests merged in 2023-04, with the labels that each got.

#429 fixed broken link
  examples/ibm-tutorial/README.md
Labels: size/XS

#431 Upgrade spire to 1.6.2
  platform/vendor/spire/chart/Chart.yaml
  platform/vendor/spire/chart/templates/server-configmap.yaml
  platform/vendor/spire/chart/templates/server-statefulset.yaml
  platform/vendor/spire/chart/values.yaml
  platform/vendor/vendor-helm-all.sh
Labels: size/M

#433 Update _index.md
  docs/content/_index.md
Labels: size/XS

#435 Update Cue v0.4.3 -> v0.5.0
  platform/00-kubernetes-minikube-setup.sh
Labels: size/XS

#441 Update minikube v1.26.1 -> v1.30.1
  platform/00-kubernetes-minikube-setup.sh
Labels: size/XS

#442 Fix linting on email address
  CODE_OF_CONDUCT.md
Labels: size/XS

#438 Update to Kyverno 1.9.2
  platform/vendor/kyverno/release/install.yaml
  platform/vendor/vendor.yaml
Labels: size/L
