Repository buildsec/frsca, pull requests merged in 2023-01, with the labels that each got.

#381 Fix gradle-pipeline example
  examples/gradle-pipeline/gradle-pipeline.cue
Labels: size/XS

#376 Create scorecards.yml
  .github/workflows/scorecards.yml
Labels: size/M

#388 Fix vendor hash of git-clone task
  platform/vendor/tekton/catalog/main/task/git-clone/0.9/git-clone.yaml
  platform/vendor/vendor.yaml
Labels: size/XS

#384 fix: workflow issues found via scorecard
  .github/workflows/docs.yaml
  .github/workflows/install-frsca.yaml
Labels: size/S

#389 change permission for docs.yaml to allow write
  .github/workflows/docs.yaml
Labels: size/XS

#390 Add CODEOWNERS file
  .github/CODEOWNERS
Labels: size/XS

#394 Update git-clone sha256
  platform/vendor/tekton/catalog/main/task/git-clone/0.9/git-clone.yaml
  platform/vendor/vendor.yaml
Labels: size/XS
