Repository buildsec/frsca, pull requests merged in 2023-02, with the labels that each got.

#397 SLSA documentation
  docs/content/docs/slsa/_index.md
  docs/content/docs/slsa/frsca-slsa.md
Labels: size/L

#399 Adjust Markdown Linting Tasks
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .prettierignore
  CODE_OF_CONDUCT.md
  Makefile
  README.md
  docs/README.md
  docs/content/docs/help/using-cue.md
  examples/cosign/README.md
  examples/maven/README.md
Labels: size/L

#401 Add OpenSSF Scorecard Badge
  README.md
Labels: size/XS

#402 Fix mascot image in docs
  README.md
Labels: size/XS

#403 Install crane on Linux, readme cleanup
  README.md
  platform/00-kubernetes-minikube-setup.sh
Labels: size/S

#406 Fixing the install of crane
  platform/00-kubernetes-minikube-setup.sh
Labels: size/XS

#405 Use installed version of crane
  .github/workflows/install-frsca.yaml
Labels: size/XS

#408 Update kyverno 1.7.5 -> 1.9.0
  platform/30-kyverno-install.sh
  platform/vendor/kyverno/release/install.yaml
  platform/vendor/vendor.yaml
Labels: size/XXL

#410 Fix kyverno upgrade
  platform/30-kyverno-install.sh
Labels: size/XS
