Repository buildsec/frsca, pull requests merged in 2025-03, with the labels that each got.

#570 Add CI Badge
  .github/workflows/all-examples.yaml
  README.md
Labels: size/L

#574 Move write permission to job level
  .github/workflows/docs.yaml
Labels: size/XS

#575 Update Cue v0.9.0 -> v0.12.0
  cue.mod/gen/github.com/tektoncd/pipeline/pkg/apis/config/default_go_gen.cue
  cue.mod/gen/github.com/tektoncd/pipeline/pkg/apis/config/events_go_gen.cue
  cue.mod/gen/github.com/tektoncd/pipeline/pkg/apis/config/store_go_gen.cue
  cue.mod/gen/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/customrun_types_go_gen.cue
  cue.mod/gen/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_types_go_gen.cue
  cue.mod/gen/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipelinerun_types_go_gen.cue
  cue.mod/gen/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/resource_types_go_gen.cue
  cue.mod/gen/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/result_types_go_gen.cue
  cue.mod/gen/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/taskrun_types_go_gen.cue
  cue.mod/gen/github.com/tektoncd/pipeline/pkg/apis/resource/v1alpha1/pipeline_resource_types_go_gen.cue
  cue.mod/gen/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/event_listener_types_go_gen.cue
  cue.mod/gen/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/trigger_binding_types_go_gen.cue
  cue.mod/gen/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/trigger_template_types_go_gen.cue
  cue.mod/gen/k8s.io/api/core/v1/types_go_gen.cue
  cue.mod/gen/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types_go_gen.cue
  cue.mod/gen/k8s.io/apimachinery/pkg/apis/meta/v1/types_go_gen.cue
  cue.mod/gen/k8s.io/apimachinery/pkg/runtime/allocator_go_gen.cue
  cue.mod/gen/k8s.io/apimachinery/pkg/runtime/codec_go_gen.cue
  cue.mod/gen/k8s.io/apimachinery/pkg/runtime/helper_go_gen.cue
  cue.mod/gen/knative.dev/pkg/apis/contexts_go_gen.cue
  cue.mod/gen/knative.dev/pkg/apis/duck/v1/cronjob_defaults_go_gen.cue
  cue.mod/gen/knative.dev/pkg/apis/duck/v1/cronjob_validation_go_gen.cue
  cue.mod/gen/knative.dev/pkg/apis/duck/v1/knative_reference_go_gen.cue
  cue.mod/gen/knative.dev/pkg/apis/duck/v1/podspec_defaults_go_gen.cue
  cue.mod/gen/knative.dev/pkg/apis/duck/v1/podspec_validation_go_gen.cue
  cue.mod/gen/time/format_go_gen.cue
  cue.mod/gen/time/time_go_gen.cue
  cue.mod/gen/time/zoneinfo_go_gen.cue
  cue.mod/gen/time/zoneinfo_read_go_gen.cue
  cue.mod/module.cue
  platform/00-kubernetes-minikube-setup.sh
Labels: size/XL

#582 Fix spacing before comment in all-examples.yaml
  .github/workflows/all-examples.yaml
Labels: size/XS

#584 fix broken links
  README.md
  docs/content/_index.md
Labels: size/XS
